name: Build NodeMobile.framework

on:
  push:
    branches:
      - node-ios-v18

env:
  SCCACHE_VERSION: 0.2.15

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: build framework
        run: |
          ./tools/ios_framework_prepare.sh

      - name: build xcframework
        run: |
          xcodebuild -create-xcframework \
            -framework out_ios/Release-iphoneos/NodeMobile.framework \
            -debug-symbols $(pwd)/out_ios/Release-iphoneos/NodeMobile.framework.dSYM \
            -framework out_ios/Release-iphonesimulator/NodeMobile.framework \
            -debug-symbols $(pwd)/out_ios/Release-iphonesimulator/NodeMobile.framework.dSYM \
            -output out_ios/NodeMobile.xcframework

      - name: Upload framework
        uses: actions/upload-artifact@v3
        with:
          name: NodeMobile.framework
          path: |
            out_ios/Release-iphoneos/NodeMobile.framework
            out_ios/Release-iphonesimulator/NodeMobile.framework

      - name: Upload xcframework
        uses: actions/upload-artifact@v3
        with:
          name: NodeMobile.xcframework
          path: out_ios/NodeMobile.xcframework
