name: Build NodeMobile.framework

on:
  push:
    branches:
      - node-ios-v18

env:
  SCCACHE_VERSION: 0.2.15

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: build framework
        run: |
          ./tools/ios_framework_prepare.sh

      - name: Upload xcframework
        uses: actions/upload-artifact@v3
        with:
          name: NodeMobile.xcframework
          path: out_ios/NodeMobile.xcframework
