name: Build from tarball

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'
      - .github/**
      - '!.github/workflows/build-tarball.yml'
  push:
    branches:
      - master
      - main
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'
      - .github/**
      - '!.github/workflows/build-tarball.yml'

env:
  FLAKY_TESTS: dontcare

jobs:
  build-tarball:
    if: github.event.pull_request.draft == false
    env:
      PYTHON_VERSION: '3.10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Make tarball
        run: |
          export DISTTYPE=nightly
          export DATESTRING=`date "+%Y-%m-%d"`
          export COMMIT=$(git rev-parse --short=10 "$GITHUB_SHA")
          ./configure && make tar -j8 SKIP_XZ=1
          mkdir tarballs
          mv *.tar.gz tarballs
      - name: Upload tarball artifact
        uses: actions/upload-artifact@v2
        with:
          name: tarballs
          path: tarballs
  test-tarball-linux:
    env:
      PYTHON_VERSION: '3.10'
    needs: build-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Download tarball
        uses: actions/download-artifact@v2
        with:
          name: tarballs
          path: tarballs
      - name: Extract tarball
        run: |
          tar xzf tarballs/*.tar.gz -C $RUNNER_TEMP
          echo "TAR_DIR=$RUNNER_TEMP/`basename tarballs/*.tar.gz .tar.gz`" >> $GITHUB_ENV
      - name: Copy directories needed for testing
        run: |
          cp -r tools/node_modules $TAR_DIR/tools
          cp -r tools/eslint-rules $TAR_DIR/tools
      - name: Build
        run: |
          cd $TAR_DIR
          make build-ci -j2 V=1
      - name: Test
        run: |
          cd $TAR_DIR
          make run-ci -j2 V=1 TEST_CI_ARGS="-p dots"
