name: test-linux

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/test-linux.yml'
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/test-linux.yml'

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: dontcare

jobs:
  test-linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test
        run: make run-ci -j2 V=1 TEST_CI_ARGS="-p actions"
