name: Timezone update
on:
  schedule:
    # Run once a week at 00:05 AM UTC on Sunday.
    - cron: 5 0 * * 0

  workflow_dispatch:

permissions:
  contents: read

jobs:
  timezone_update:
    permissions:
      contents: write  # to push local changes (gr2m/create-or-update-pull-request-action)
      pull-requests: write  # to create a PR (gr2m/create-or-update-pull-request-action)

    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nodejs/node
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout unicode-org/icu-data
        uses: actions/checkout@v3
        with:
          path: icu-data
          persist-credentials: false
          repository: unicode-org/icu-data

      - run: ./tools/update-timezone.mjs

      - name: Open Pull Request
        uses: gr2m/create-or-update-pull-request-action@6720400cad8e74d7adc64640e4e6ea6748b83d8f  # Create a PR or update the Action's existing PR
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          body: |
            This PR was generated by tools/timezone-update.yml.

            Updates the ICU files as per the instructions present in https://github.com/nodejs/node/blob/main/doc/contributing/maintaining-icu.md#time-zone-data

            To test, build node off this branch & log the version of tz using
            ```js
            console.log(process.versions.tz)
            ```
          branch: actions/timezone-update
          commit-message: 'deps: update timezone'
          labels: dependencies
          title: 'deps: update timezone'
          reviewers: \@nodejs/i18n-api
